# Generated by Django 4.2.7 on 2023-11-17 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(choices=[('Orthology', 'Orthology'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology')], max_length=50)),
                ('consultation_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofvisit', models.DateTimeField(auto_now_add=True)),
                ('observation_details', models.TextField()),
                ('diagnosis_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dateofbirth', models.DateField()),
                ('age', models.IntegerField()),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('registernumber', models.CharField(editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Receptionist', 'Receptionist')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_joining', models.DateField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255)),
                ('time_of_consumption', models.CharField(max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.medicine')),
                ('medicine_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appcms.medicinehistory')),
            ],
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='choose_test',
            field=models.ManyToManyField(blank=True, to='appcms.test'),
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.doctor'),
        ),
        migrations.AddField(
            model_name='medicinehistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.patient'),
        ),
        migrations.CreateModel(
            name='MedicineBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('medicine_bill_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('medicine_prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.medicineprescription')),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('lab_report_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.doctoravailability')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.patient')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.staff')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.medicinehistory')),
            ],
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('test_bill_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.doctoravailability')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.patient')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.staff')),
                ('tested_tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.medicinehistory')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='staff',
            field=models.OneToOneField(limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='appcms.staff'),
        ),
        migrations.CreateModel(
            name='AppointmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bill_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('appointed_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.doctoravailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField(auto_now_add=True)),
                ('token', models.CharField(editable=False, max_length=10, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.doctoravailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.patient')),
            ],
        ),
    ]
