# Generated by Django 4.2.7 on 2023-11-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineprescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='time_of_consumption',
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcms.patient'),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcms.staff'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255)),
                ('time_of_consumption', models.CharField(max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.medicine')),
                ('medicine_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_details', to='appcms.medicineprescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('prescribed_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.prescriptiondetail')),
            ],
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='medicines',
            field=models.ManyToManyField(through='appcms.PrescriptionDetail', to='appcms.medicine'),
        ),
    ]
