# Generated by Django 4.2.7 on 2023-11-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0003_appointment_bill_no_alter_medicinebill_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='bill_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
