# Generated by Django 4.2.7 on 2023-11-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0004_alter_appointment_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='test_bill_id',
            field=models.CharField(default=1, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='days',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentbill',
            name='bill_no',
            field=models.CharField(default=1, editable=False, max_length=10),
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='tests',
        ),
        migrations.AlterField(
            model_name='medicinebill',
            name='medicine_prescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.medicinehistory'),
        ),
        migrations.AlterField(
            model_name='medicinequantity',
            name='prescribed_medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_quantities', to='appcms.prescriptiondetail'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='medicine_prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_details', to='appcms.medicinehistory'),
        ),
        migrations.DeleteModel(
            name='MedicinePrescription',
        ),
        migrations.AddField(
            model_name='labreport',
            name='tests',
            field=models.ManyToManyField(to='appcms.test'),
        ),
    ]
