# Generated by Django 4.2.7 on 2023-11-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0005_labreport_test_bill_id_prescriptiondetail_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbill',
            name='bill_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='test_bill_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
