# Generated by Django 4.2.7 on 2023-11-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcms', '0006_alter_appointmentbill_bill_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinehistory',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcms.doctoravailability'),
        ),
    ]
